apiVersion: v1
kind: Service
metadata:
  name: {{ include "nex.fullname" . }}
  labels:
    {{- include "nex.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "nex.selectorLabels" . | nindent 4 }}
    component: backend