apiVersion: v1
kind: Namespace
metadata:
  name: nex
  labels:
    name: nex
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: nex-dev
  labels:
    name: nex-dev
    environment: development