apiVersion: v1
kind: Secret
metadata:
  name: nex-secrets
  namespace: nex
type: Opaque
data:
  # API密钥 (base64编码)
  api-key: bmV4LWFwaS1rZXktc2VjcmV0  # nex-api-key-secret
  
  # 数据库密码 (如果使用外部数据库)
  db-password: c2VjdXJlLXBhc3N3b3Jk  # secure-password
  
  # JWT密钥
  jwt-secret: and1dC1zZWNyZXQta2V5LWZvci1qd3Q=  # jwt-secret-key-for-jwt
  
  # 监控密钥
  monitoring-token: bW9uaXRvcmluZy10b2tlbi1zZWNyZXQ=  # monitoring-token-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: nex-tls
  namespace: nex
type: kubernetes.io/tls
data:
  # TLS证书 (需要替换为实际证书)
  tls.crt: LS0tLS1CRUdJTi... # 实际部署时需要替换
  tls.key: LS0tLS1CRUdJTi... # 实际部署时需要替换