apiVersion: v1
kind: Service
metadata:
  name: nex-service
  namespace: nex
  labels:
    app: nex
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: nex
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nex-service-headless
  namespace: nex
  labels:
    app: nex
    component: backend
spec:
  selector:
    app: nex
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  clusterIP: None  # Headless service for direct pod access

---
apiVersion: v1
kind: Service
metadata:
  name: nex-external-service
  namespace: nex
  labels:
    app: nex
    component: backend
spec:
  selector:
    app: nex
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
    nodePort: 30080
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
    nodePort: 30051
  type: NodePort  # 用于外部访问